version: "3.8"
services:
  nginx:
      image: nginx:latest
      container_name: nginx-proxy
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
      depends_on:
        - app1
        - app2

  postgres-db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: felipe
      POSTGRES_DB: bdtemp
    ports:
      - "5432:5432"
  app1:
    container_name: topeducation1
    image: felipediaz1/topeducation:latest
    ports:
      - "8091:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bdtemp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=felipe
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - postgres-db
  app2:
    container_name: topeducation2
    image: felipediaz1/topeducation:latest
    ports:
      - "8092:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bdtemp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=felipe
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - postgres-db